### ISSUE TITLE
有才!

### ISSUE THREAD

**Issue by Bian-Sh** [yhsj0919/ELauncher#1]
把群里的桌面试了一遍，你的体验最好了，有才！

顺便问下锁屏画面能改不？

**Comment by yhsj0919** [comment]
锁屏界面改不了,暂时没有开放接口

**Comment by Bian-Sh** [comment]
可不可以把那个通知栏上的气泡去掉：
就是那句：墨水屏正在其他应用的上层显示内容
我记得群里的 4键 悬浮球 这款应用是不会显示这个东西的，说明可以搞掉的

**Comment by Bian-Sh** [comment]
> 锁屏界面改不了,暂时没有开放接口

可以通过类似于啥反射这样的黑科技去改吗？
